CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_DISPLAY=n
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_IDLE_TIMEOUT=30000
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=300000
# I2C가 디스플레이에 딸려 켜졌다가 같이 꺼지는 걸 방지
CONFIG_I2C=y
CONFIG_I2C_NRFX=y

# 트랙패드 드라이버 확실히 포함
CONFIG_INPUT=y
CONFIG_INPUT_AZOTEQ_IQS5XX=y
CONFIG_ZMK_SLEEP_ON_BLE_DISCONNECT=y
CONFIG_ZMK_SLEEP_DISCONNECT_TIMER=30000
